config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :sections
  resources :courses
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :grader_applications
  resources :permission_requests
  resources :inbox_applications

  put 'inbox_applications/approve'
  put 'inbox_applications/deny'
  put 'permission_requests/approve'
  put 'permission_requests/deny'

  get 'course_fetcher_ui/index'
  post 'course_fetcher_ui/fetch_courses'
  
  #commenting the default home index thing out. This is to have a landing page.
  #get 'home/index'
  root 'home#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
# Basic controller for the home page
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  # List all elements in the root page
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<% if false %>
NOTE: The NavBar template code used below to create the NavBar is located at: https://getbootstrap.com/docs/5.3/components/navbar/
<% end %>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Home', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to "Course Catalog", courses_path, class:"nav-link"%>
      </li>

      <li class="nav-item">
        <%= link_to "Section Catalog", sections_path, class:"nav-link"%>
      </li>


      <% if current_user.role == "instructor" && current_user.user_approved %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Recommendations
        </a>
        <div class="dropdown-menu">
          <%= link_to "View Recommendations", recommendations_path, class:"dropdown-item"%>
           <% if current_user.role == "instructor" && current_user.user_approved == true %>
           <%= link_to "Create New Recommendation", new_recommendation_path, class:"dropdown-item" %>
           <% end %>
        </div>
      </li>
      
      <% elsif current_user.role == "student" %>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Grader Applications
        </a>
        <div class="dropdown-menu">
          <%= link_to "Submitted Applications", grader_applications_path, class:"dropdown-item"%>
          <% if current_user.role == "student" %>
          <%= link_to 'Create New Application', new_grader_application_path, class:"dropdown-item" %>
          <%end%>
        </div>
      </li> 
        <% end %>
   <% if current_user.role == "admin" && current_user.user_approved%>

     <li class="nav-item">
       <%= link_to "Permissions Requests", permission_requests_path, class:"nav-link"%>
      </li>

      <li class="nav-item">
        <%= link_to "Recommendations", recommendations_path, class:"nav-link"%>
      </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Grader Applications
        </a>
        <div class="dropdown-menu">
           <%= link_to "Grader Applications", grader_applications_path, class:"dropdown-item"%>
           <%= link_to "Applications Pending Approval", inbox_applications_path, class:"dropdown-item"%>
        </div>
      <% end %>

      </ul> 
      <ul class="navbar-nav ml-auto">
      <% if current_user.role == "admin" && current_user.user_approved %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-tools" viewBox="0 0 16 16">
          <path d="M1 0 0 1l2.2 3.081a1 1 0 0 0 .815.419h.07a1 1 0 0 1 .708.293l2.675 2.675-2.617 2.654A3.003 3.003 0 0 0 0 13a3 3 0 1 0 5.878-.851l2.654-2.617.968.968-.305.914a1 1 0 0 0 .242 1.023l3.27 3.27a.997.997 0 0 0 1.414 0l1.586-1.586a.997.997 0 0 0 0-1.414l-3.27-3.27a1 1 0 0 0-1.023-.242L10.5 9.5l-.96-.96 2.68-2.643A3.005 3.005 0 0 0 16 3c0-.269-.035-.53-.102-.777l-2.14 2.141L12 4l-.364-1.757L13.777.102a3 3 0 0 0-3.675 3.68L7.462 6.46 4.793 3.793a1 1 0 0 1-.293-.707v-.071a1 1 0 0 0-.419-.814L1 0Zm9.646 10.646a.5.5 0 0 1 .708 0l2.914 2.915a.5.5 0 0 1-.707.707l-2.915-2.914a.5.5 0 0 1 0-.708ZM3 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026L3 11Z"/>
          </svg>
          Admin Actions
        </a>
        <div class="dropdown-menu">
          <%= link_to "Permissions Requests", permission_requests_path, class:"dropdown-item"%>
           <%= link_to "Grader Applications", inbox_applications_path, class:"dropdown-item"%>
           <div class="dropdown-divider"></div>
           <%= link_to "Go to Course Fetcher", course_fetcher_ui_index_path, class:"dropdown-item"%>
           <div class="dropdown-divider"></div>
           <%= link_to "Create a New Course", new_course_path, class:"dropdown-item"%>
           <%= link_to "Create a New Section", new_section_path, class:"dropdown-item" %>
        </div>
      </li>
      <% end %>

       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
           <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
           <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
          </svg>
          <%= current_user.first_name %>
        </a>
        <div class="dropdown-menu">
            <% if current_user.email != "admin.1@osu.edu" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class:"dropdown-item"%>
            <%end%>
            <a class="dropdown-item" href="https://github.com/cse-3901-sharkey/2023-SU-Team-1-Lab-2/blob/main/README.md" target="_blank">
            System Help
        </a>
            <%= link_to "Sign Out", destroy_user_session_path, class:"dropdown-item", data: { turbo_method: :delete }%>
        </div>
      </li>

     <% else %>
      
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
      </li>

        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
      </li>
     <% end %>
    </ul> 
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome to the OSU Student Grader Management System</h1>
<strong>Click on the links on the navigation bar to traverse the site.</strong>
<% if current_user %>
    <% if !current_user.user_approved && (current_user.role == "instructor" || current_user.role == "admin") %>
        <p>You currently have student level permissions</p>      
        <p>Your request to have <%= current_user.role%> level permissions is pending. Contact an Admin for further details.</p>
    <% else %>       
         <p>You currently have <%= current_user.role%> level permissions</p>
         <% if current_user.role == "student" && !current_user.user_approved %>
         <p>If you requested to have admin/instructor permissions, it has been denied. Contact an admin for further details.</p> 
         <% end %>         
    <% end %>   
<% end %>