config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :sections
  resources :courses
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :grader_applications
  resources :permission_requests
  resources :inbox_applications

  put 'inbox_applications/approve'
  put 'inbox_applications/deny'
  put 'permission_requests/approve'
  put 'permission_requests/deny'

  get 'course_fetcher_ui/index'
  post 'course_fetcher_ui/fetch_courses'
  
  #commenting the default home index thing out. This is to have a landing page.
  #get 'home/index'
  root 'home#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/section.rb
# frozen_string_literal: true

# Section model of the course. Each section represents a class taught by different professor or in different time.\
# @belongs_to Course
# @key [Integer] section_id
# @requires section_id is UNIQUE and must PRESENT
# @requires campus must PRESENT
# @requires term_id must PRESENT
# @requires section_number is UNIQUE and must PRESENT with format of XXXX
# @requires meeting_days is at most 7-digits from 1-7 and number must be unique
# @requires course must PRESENT
# @requires end_time must AFTER start_time
# @updates catalog_number = self.course.catalog_number
class Section < ApplicationRecord
  self.primary_key = :section_id
  default_scope { order(catalog_number: :asc, section_number: :asc) }
  belongs_to :course, class_name: 'Course', foreign_key: 'course_id', required: false
  validates :section_id, uniqueness: true, presence: true
  validates :campus, presence: true
  validates :term_id, presence: true
  validates :section_number, presence: true
  validate :auto_fill_or_validate_section_number
  validate :validate_meeting_days
  validates :course, presence: true
  validate :end_time_after_start_time
  validates :instructor_email, allow_blank: true, allow_nil: true, format: { with: /\b[a-z]+\.([1-9][0-9]*)@osu\.edu\z/i, message: "Instructor email must follow the lastname.\#@osu.edu convention or leave blank." }
  before_save :update_field

  # When user enters number values for the days of the week available, ie 1 = Monday 2 = Tuesday etc.
  def format_days_of_week
    days_names = %w(Mon Tue Wed Thu Fri Sat Sun)
    formatted_days = days_of_week.chars.map { |day| days_names[day.to_i - 1] }
    formatted_days.join(', ')
    return 'Online, N/A or TBA' if (days_of_week == '') || formatted_days.nil?

    formatted_days
  end

   # If the info is nil, like for sections times, or if section is only, display "N/A or TBA" to the user
  def self.nil_wrapper(info)
    wrapped_info = info
    wrapped_info = 'N/A or TBA' if (info == '') || info.nil?
    wrapped_info
  end

  # Drop down section text that includes all information that is needed
  def section_identifier
    course_description = self.course.course_name
    course_description = self.course.short_description if !self.course.short_description.nil?
    time_start_str = self.time_start ? self.time_start.strftime("%I:%M %p") : ""
    time_end_str = self.time_end ? self.time_end.strftime("%I:%M %p") : ""
    "CSE #{self.course.catalog_number} - #{course_description}(#{self.section_number}) - #{self.instructor_name} - #{self.format_days_of_week} - #{time_start_str} - #{time_end_str} - #{self.location}, Grader Positions Remaining: #{self.num_required_graders - self.current_num_required_graders}"
  end

  def self.ransackable_attributes(auth_object = nil)
    ["campus", "catalog_number", "course_id", "created_at", "current_num_required_graders", "days_of_week", "instructor_email", "instructor_name", "location", "num_required_graders", "section_id", "section_number", "term_id", "time_end", "time_start", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["course"]
  end

   # Updates the related course and grader values when section is created
  def update_field
    course = Course.find_by(course_id: self.course_id)
    self.catalog_number = course&.catalog_number
    self.num_required_graders ||= 1
    self.current_num_required_graders ||= 0
    self.current_num_required_graders = [self.current_num_required_graders, 0].max
  end

  private

  # Validation that user is entering accurate integers that can be mapped.
  def validate_meeting_days
    return unless days_of_week.present?

    valid_digits = %w[1 2 3 4 5 6 7]
    invalid_chars = days_of_week.chars.uniq - valid_digits

    if invalid_chars.any?
      errors.add(:days_of_week, 'Meeting days should only contain digits 1 to 7.')
    elsif days_of_week.chars.uniq.size > 7
      errors.add(:days_of_week, 'Meeting days should have at most 7 distinct digits.')
    end
  end

   # Auto fills section number if blank, or validates that it is 4 digits
  def auto_fill_or_validate_section_number
    return if section_number.match?(/\A\d{4}\z/)

    self.section_number = self.section_number.rjust(4, '0') if section_number.length < 4
    if self.section_number.match?(/\A\d{4}\z/)
      return
    else
      errors.add(:section_number, "Section number can only be 4-digits. Actual: #{:section_number}")
    end
  end

  # Validates that the end time schedule is after the start time
  def end_time_after_start_time
    return if time_end.blank? || time_start.blank?
    errors.add(:time_end, "must be after the start time") if time_end < time_start
  end
end

app/controllers/sections_controller.rb
# Controller for the sections.
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]
  before_action :is_admin, only: %i[ new edit create destroy ]

  # GET /sections or /sections.json
  def index
    @q = Section.ransack(params[:q])
    @sections = @q.result
    @pagy, @sections = pagy(Section.ransack(params[:q]).result(distinct: true))
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)
    @section.id = generate_section_id if @section.section_id.nil?

    respond_to do |format|
      if @section.save
        format.html { redirect_to section_url(@section), notice: 'Section has been created successfully' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to section_url(@section), notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_section
    @section = Section.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def section_params
    params.require(:section).permit(:section_id, :section_number, :course_id, :catalog_number, :term_id, :campus, :days_of_week, :time_start, :time_end, :location, :instructor_name, :instructor_email, :current_num_required_graders, :num_required_graders)
  end

  # Assign section id for new sections. Always assign 1000 to the current maximum +1.
  def generate_section_id
    max_section_id = Section.maximum(:Section_id)
    return max_section_id.nil? ? 1000 : max_section_id + 1
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <form>

  <div class="row">
    <div class="col">
      <%= form.label :section_number, 'Section Number (4-digit)', style: "display: block" %>
    <%= form.text_field :section_number, class:'form-control' %>
    </div>
    <div class="col">
      <%= form.label :term_id, 'Term ID (4-digit)', style: "display: block" %>
    <%= form.text_field :term_id, class:'form-control' %>
    </div>
  </div>

 <% course_options = options_for_select(Course.all.map { |course| [course.course_identifier, course.course_id] }) %>
<div>
  <%= form.label :course_id, 'Course of the section', style: "display: block" %>
  <%= form.select :course_id, Course.all.map { |course| [course.course_identifier, course.course_id] } %>
</div>

  <div>
    <%= form.label :campus, style: "display: block" %>
    <%= form.text_field :campus, class:'form-control' %>
  </div>

  <div>
    <%= form.label :days_of_week, 'Meeting days (1-7 for Mon-Sun, up to 7 digits)', style: "display: block" %>
    <%= form.text_field :days_of_week, class:'form-control' %>
  </div>

  <div class="row">
    <div class="col">
         <%= form.label :time_start, 'Start Time of Meeting', style: "display: block" %>
    <%= form.time_field :time_start, class:'form-control' %>
    </div>
    <div class="col">
    <%= form.label :time_end,'End Time of Meeting', style: "display: block" %>
    <%= form.time_field :time_end, class:'form-control' %>
    </div>
  </div>

  <div>
    <%= form.label :location, 'Classroom Location', style: "display: block" %>
    <%= form.text_field :location, class:'form-control' %>
  </div>

  <div>
    <%= form.label :instructor_name, style: "display: block" %>
    <%= form.text_field :instructor_name, class:'form-control' %>
  </div>

  <div>
    <%= form.label :instructor_email, style: "display: block" %>
    <%= form.text_field :instructor_email, class:'form-control' %>
  </div>

<div class="row">
    <div class="col">
        <%= form.label :num_required_graders, 'Required Number of Graders (Default: 1)',style: "display: block" %>
      <%= form.number_field :num_required_graders, class:'form-control' %>
    </div>
    <div class="col">
  <%= form.label :current_num_required_graders, 'Current Number of Graders (Default: 0)', style: "display: block" %>
    <%= form.number_field :current_num_required_graders, class:'form-control' %>
    </div>
  </div>
</br>
  <div>
    <%= form.submit  class:'btn btn-outline-success'%>

 <%= link_to "Back to courses", courses_path, class:'btn btn-outline-primary' %>


  </div>
  </form>
<% end %>

app/views/sections/_section.html.erb
<div id="<%= dom_id section %>">
<% @course = @section.course%>

  <h3>Section information for CSE <%= section.catalog_number %></h3>
  

  <p>
    <strong>Course Identifier:</strong>
    <%= Course.find_by(course_id: section.course_id).course_identifier %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= section.section_id %>
  </p>

  <p>
    <strong>Section number:</strong>
    <%= section.section_number %>
  </p>

<!--  <p>-->
<!--    <strong>Course:</strong>-->
    <%#= section.course_id %>
<!--  </p>-->

<!--  <p>-->
<!--    <strong>Catalog number:</strong>-->
    <%#= section.catalog_number %>
<!--  </p>-->

  <p>
    <strong>Term:</strong>
    <%= section.term_id %>
  </p>

  <p>
    <strong>Campus:</strong>
    <%= section.campus %>
  </p>

  <p>
    <strong>Days of the week:</strong>
    <%= section.format_days_of_week %>
  </p>
  
  <p>
    <strong>Time Start:</strong>
    <% if section.time_start != nil%>
    <%= section.time_start.strftime("%I:%M %p")%>
    <%else%>
    <td><%= Section.nil_wrapper(section.time_start) %></td>
    <% end %>
  </p>

  <p>
    <strong>Time End:</strong>
    <% if section.time_end != nil%>
    <%= section.time_end.strftime("%I:%M %p")%>
    <%else%>
    <td><%= Section.nil_wrapper(section.time_end) %></td>
    <% end %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= Section.nil_wrapper(section.location) %>
  </p>

  <p>
    <strong>Instructor name:</strong>
    <%= Section.nil_wrapper(section.instructor_name) %>
  </p>

  <p>
    <strong>Instructor email:</strong>
    <%= Section.nil_wrapper(section.instructor_email) %>
  </p>

  <p>
    <strong>Num required graders:</strong>
    <%= section.num_required_graders %>
  </p>

  <p>
    <strong>Current num required graders:</strong>
    <%= section.current_num_required_graders %>
  </p>

 <p> 
  <div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn active">
 <%= link_to "Go to Course Details", course_path(@course), :class=>"btn btn-primary"%>
  </label>
  <% if current_user && current_user.role == "admin" %>
   <label class="btn">
     <%= link_to "Edit this section", edit_section_path(@section), :class => "btn btn-outline-success " %>
      </label>
    <label class="btn">
    <%= button_to "Destroy this section", @section, method: :delete, :class => "btn btn-outline-danger" %>
      </label>
  <% end %>
  </div>
  </p>

</div>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Show this section", @section %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<h3>Section Catalog
 <% if current_user && current_user.role == "admin" %>
<div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
  <label class="btn active">
 <%= link_to "Go to Course Fetcher", course_fetcher_ui_index_path, class:"btn btn-outline-primary float-right"%>
  </label>
  <label class="btn">
   <%= link_to "New section", new_section_path , class:"btn btn-outline-success float-right" %>
    </label>
</div> 
  <% end %>
    <form class="float-right form-inline">
  <%= search_form_for @q do |f| %>
  <%= f.search_field :course_id_or_catalog_number_or_section_id_or_section_number_or_time_start_or_time_end_or_instructor_name_or_instructor_email_or_location_cont, class:'form-control mr-sm-2 float-right' %>
  <%= f.submit :submit, class:'btn btn-outline-success my-2 my-sm-o float-right' %>
  <%end %>
  </form>
</h3>
Only Course Catalog Number or Course ID can be used as search identifiers.
For sorting, click on the column you would like to sort.

  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
      <th><%= sort_link(@q, :section_id, class:'text-white') %></th>
      <th><%= sort_link(@q, :catalog_number, 'Course Identifier', class:'text-white') %></th>
      <th><%= sort_link(@q, :time_start, 'Time', class:'text-white') %></th>
      <th><%= sort_link(@q, :instructor_name, class:'text-white') %></th>
      <th>Term ID</th>
      <th>Operation</th>
    </tr>
    </thead>
    <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.id %></td>
        <% course = Course.find_by(course_id: section.course_id) %>
        <td><%= course.course_identifier %></td>
        <td>
        <%if section.time_start != nil %>
          <%= section.time_start.strftime("%I:%M %p") %> - <%= section.time_end.strftime("%I:%M %p") %>
        <%else%>
          <%= Section.nil_wrapper(section.time_start) %>
        <%end%>
        
        </td>
        <td><%= Section.nil_wrapper(section.instructor_name) %></td>
        <td><%= section.term_id %></td>
        <td><%= link_to "Show this section", section, :class => "btn btn-outline-primary btn-sm"%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <strong>In total of <%= Section.count %> sections in the database</strong>
<div class='float-right'> 
<%== pagy_bootstrap_nav(@pagy) %>
</div>
</div>

app/views/sections/new.html.erb
<h3>New section</h3>

<%= render "form", section: @section %>

<br>

app/views/sections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @section %>
<% @course = @section.course%>