config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :sections
  resources :courses
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :grader_applications
  resources :permission_requests
  resources :inbox_applications

  put 'inbox_applications/approve'
  put 'inbox_applications/deny'
  put 'permission_requests/approve'
  put 'permission_requests/deny'

  get 'course_fetcher_ui/index'
  post 'course_fetcher_ui/fetch_courses'
  
  #commenting the default home index thing out. This is to have a landing page.
  #get 'home/index'
  root 'home#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/grader_application.rb
class GraderApplication < ApplicationRecord
  before_create :set_status_to_pending
  belongs_to :section
  validates :section, presence: true
  validates :grade_received, presence: true, length: { maximum: 2, minimum: 1 }
  validates :grade_received, inclusion: { in: %w(A A- B+ B B- C+ C C- D+ D E a a- b+ b b- c+ c c- d+ d e PA pa I i EM em K k NP np PE pe S s U u W w) }
  validate :end_time_after_start_time
  validate :unique_pair_and_section, on: :create

  # When user enters number values for the days of the week available, ie 1 = Monday 2 = Tuesday etc.
  def format_days_of_week
    days_names = %w(Mon Tue Wed Thu Fri Sat Sun)
    formatted_days = days_of_the_week_available.chars.map { |day| days_names[day.to_i - 1] }
    formatted_days.join(', ')
    return 'N/A' if (days_of_the_week_available == '') || formatted_days.nil?
    formatted_days
  end

  private

  # Validates that the end time schedule is after the start time
  def end_time_after_start_time
    return if time_end_available.blank? || time_start_available.blank?
    errors.add(:time_end_available, "must be after the start time") if time_end_available <= time_start_available
  end

  def set_status_to_pending
    self.status = 'Pending'
  end

   # Validates that user is not submitting an application to a section they already applied for.
  def unique_pair_and_section
    existing_application = GraderApplication.find_by(section: self.section, email: self.email)

    if existing_application && existing_application != self
      errors.add(:base, "You have already submit an application of this section.")
    end
  end

end

app/controllers/grader_applications_controller.rb
# Controller for Grader Application page
class GraderApplicationsController < ApplicationController
  before_action :set_grader_application, only: %i[ show edit update destroy ]
  before_action :authenticate_student, only: [:new, :create]
  before_action :no_instructor
  before_action :no_pending_admin

  # GET /grader_applications or /grader_applications.json
  def index
    @grader_applications = GraderApplication.all
    @pagy, @grader_applications = pagy(@grader_applications)
  end

  # GET /grader_applications/1 or /grader_applications/1.json
  def show
  end

  # GET /grader_applications/new
  def new
    @grader_application = GraderApplication.new
  end

  # GET /grader_applications/1/edit
  def edit
  end

  def create
    @grader_application = GraderApplication.new(grader_application_params)

    respond_to do |format|
      if @grader_application.save
        format.html { redirect_to grader_application_url(@grader_application), notice: "Grader application was successfully created." }
        format.json { render :show, status: :created, location: @grader_application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grader_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grader_applications/1 or /grader_applications/1.json
  def update
    respond_to do |format|
      if @grader_application.update(grader_application_params)
        format.html { redirect_to grader_application_url(@grader_application), notice: "Grader application was successfully updated." }
        format.json { render :show, status: :ok, location: @grader_application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grader_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grader_applications/1 or /grader_applications/1.json
  def destroy
    @grader_application.destroy
    respond_to do |format|
      format.html { redirect_to grader_applications_url, notice: "Grader application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_grader_application
    @grader_application = GraderApplication.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def grader_application_params
    params.require(:grader_application).permit(:first_name, :last_name, :email, :course_id, :section_id, :schedule, :grade_received, :days_of_the_week_available, :time_start_available, :time_end_available)
  end

  # Authenticate if the current user is a student
  def authenticate_student
    unless current_user&.student?
      redirect_to root_path, alert: 'You must be a student to apply for a grader position.'
    end
  end

  # Sends back instructor user back for pages that is not open for instructors
  def no_instructor
    if current_user && current_user.role == 'instructor'
      redirect_to root_path, alert: 'You do not have access for this page.'
    end
  end
end

app/views/grader_applications/_application.html.erb
<div id="<%= dom_id grader_application %>">

  <h3>
    Application ID <%= grader_application.id %>: <%= grader_application.name %>
  </h3>
  <p>
    <strong>Email:</strong>
    <%= grader_application.email %>
  </p>
  <p>
    <strong>Course and Section:</strong>
    Course ID: <%= grader_application.course_id %> , Section ID: <%= grader_application.section_id %>
  </p>
  <p>
    <strong>Schedule/Availability:</strong>
    <%= grader_application.schedule %>
  </p>

</div>

app/views/grader_applications/_form.html.erb
<%= form_with(model: grader_application) do |form| %>
  <% if grader_application.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(grader_application.errors.count, "error") %> prohibited this grader application from being saved:</h2>

      <ul>
        <% grader_application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<strong>Contact Details:</strong>

<form>
  <div class="row">
    <div class="col">
      <%= form.label :first_name, 'First Name', style: "display: block"%>
      <%= form.text_field :first_name, value: current_user.first_name, autofocus: true, autocomplete: "first_name", class: "form-control", readonly: true %>
    </div>
    <div class="col">
       <%= form.label :last_name, 'Last Name', style: "display: block"%>
       <%= form.text_field :last_name, value: current_user.last_name, autofocus: true, autocomplete: "last_name", class: "form-control", readonly: true %>
    </div>
  </div>


<div>
  <%= form.label :email, 'Email', style: "display: block"%>
  <%= form.text_field :email, value: current_user.email, autofocus: true, autocomplete: "email", class: "form-control", readonly: true %>
</div>
</br>
<strong>Course Information:</strong>
</br>
<% section_options = options_for_select(Section.all.map { |section| [section.section_identifier, section.section_id] }) %>
<div>
  <%= form.label :section_id, 'Section', style: "display: block" %>
  <%= form.select :section_id, section_options, class:"form-control"  %>
</div>

</br>
 <div class = "field form-group">
    <%= form.label :grade_received, style: "display: block" %>
    <%= form.text_field :grade_received, autofocus: true, autocomplete: "grade_received", class: "form-control", :placeholder => "Example: A-"%>
  </div>
 
  </br><strong>Your Availability:</strong></br>


 <div class="row">
    <div class="col">
    <%= form.label :time_start_available, 'Time Start Available', style: "display: block" %>
    <%= form.time_field :time_start_available, autofocus: true, autocomplete: "time_start_available", class: "form-control"%>
    </div>
    <div class="col">
        <%= form.label :time_end_available, 'Time End Available', style: "display: block" %>
    <%= form.time_field :time_end_available, autofocus: true, autocomplete: "time_end_available", class: "form-control"%>
  </div>
  </div>
  
  <div>
    <%= form.label :days_of_the_week_available, 'Meeting days (1-7 for Mon-Sun, up to 7 digits)', style: "display: block" %>
    <%= form.text_field :days_of_the_week_available, class:"form-control", :placeholder => "Example (for Monday): 1"%>
  </div>

</br>
  <div class = "actions">
    <%= form.submit class:'btn btn-outline-success' %>
  </div>
</form>
<% end %>

app/views/grader_applications/_form_show.html.erb
<%= form_with(model: grader_application) do |form| %>
<fieldset disabled>
  <%= form_with(model: grader_application) do |form| %>
  <% if grader_application.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(grader_application.errors.count, "error") %> prohibited this grader application from being saved:</h2>

      <ul>
        <% grader_application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<strong>Contact Details:</strong>

<form>
  <div class="row">
    <div class="col">
      <%= form.label :first_name, 'First Name', style: "display: block"%>
      <%= form.text_field :first_name, value: current_user.first_name, autofocus: true, autocomplete: "first_name", class: "form-control", readonly: true %>
    </div>
    <div class="col">
       <%= form.label :last_name, 'Last Name', style: "display: block"%>
       <%= form.text_field :last_name, value: current_user.last_name, autofocus: true, autocomplete: "last_name", class: "form-control", readonly: true %>
    </div>
  </div>


<div>
  <%= form.label :email, 'Email', style: "display: block"%>
  <%= form.text_field :email, value: current_user.email, autofocus: true, autocomplete: "email", class: "form-control", readonly: true %>
</div>
</br>
<strong>Course Information:</strong>
</br>
<div>
  <%= form.label :course_name, 'Course Name', style: "display: block" %>
  <%= form.text_field :section_id, autofocus: true, autocomplete: "email", class: "form-control", value: grader_application.section.course.course_name %>
</div>

<% section_options = options_for_select(Section.all.map { |section| [section.section_identifier, section.section_id] }) %>
<div>
  <%= form.label :section_id, 'Section ID', style: "display: block" %>
  <%= form.text_field :section_id, autofocus: true, autocomplete: "email", class: "form-control", value: grader_application.section_id  %>
</div>

<div>
    <%= form.label :location, 'Location', style: "display: block" %>
    <%= form.text_field :location, value: grader_application.section.location, class:"form-control"%>
  </div>

 <div>
    <%= form.label :days_of_the_week_available, 'Section Meeting Days', style: "display: block" %>
    <%= form.text_field :days_of_the_week_available, value: grader_application.section.format_days_of_week, class:"form-control", :placeholder => "Example (for Monday): 1"%>
  </div>

 <div class="row">
    <div class="col">
    <%= form.label :section_time_start, 'Class Start Time', style: "display: block" %>
     <%  if grader_application.section.time_start != nil %>
    <%= form.text_field :section_id_time_start, value:grader_application.section.time_start.strftime("%I:%M %p"),  autofocus: true, autocomplete: "time_start_available", class: "form-control"%>
    <%else%>
       N/A
    <%end%>
    
    </div>
    <div class="col">
    <%= form.label :section_end, 'Class End Time', style: "display: block" %>
      <%  if grader_application.section.time_end != nil %>
    <%= form.text_field :section_id_time_end, value:grader_application.section.time_end.strftime("%I:%M %p"),  autofocus: true, autocomplete: "time_start_available", class: "form-control"%>
      <%else%>
     N/A
    <%end%>
    </div>
  </div>

<div class = "field form-group">
    <%= form.label :grade_received, style: "display: block" %>
    <%= form.text_field :grade_received, autofocus: true, autocomplete: "grade_received", class: "form-control", :placeholder => "Example: A-"%>
  </div>

  </br><strong>Availability Provided:</strong></br>

 <div class="row">
    <div class="col">
    <%= form.label :time_start_available, 'Available Start Time', style: "display: block" %>
    <%  if grader_application.time_start_available != nil %>
    <%= form.time_field :time_start_available, autofocus: true, autocomplete: "time_start_available", class: "form-control"%>
     <%else%>
       N/A
      <%end%>
    </div>
    <div class="col">
        <%= form.label :time_end_available, 'Available End Time', style: "display: block" %>
         <%  if grader_application.time_end_available != nil %>
    <%= form.time_field :time_end_available, autofocus: true, autocomplete: "time_end_available", class: "form-control"%>
    <%else%>
      N/A
      <%end%>
  </div>
  </div>
  
  <div>
    <%= form.label :days_of_the_week_available, 'Available Meeting Days', style: "display: block" %>
    <%= form.text_field :days_of_the_week_available, value: grader_application.format_days_of_week, class:"form-control", :placeholder => "Example (for Monday): 1"%>
  </div>

 

</br>
  
<% end %>

  </fieldset>
<% end %>

app/views/grader_applications/edit.html.erb
<h3>Editing Grader Application 

<div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
  <label class="btn active">
 <%= link_to "View", @grader_application, class:"btn btn-outline-primary float-right" %> 
  </label>
  <label class="btn">
     <%= link_to "Back to Grader Applications", grader_applications_path, class:"btn btn-outline-primary float-right" %>
    </label>
</div> 


   </h3>
   </br>

<%= render "form", grader_application: @grader_application %>

<br>

app/views/grader_applications/index.html.erb
<h3>Applications 
<%if current_user.role=='student'%>
<%= link_to 'Create New', new_grader_application_path, class:"btn btn-outline-success float-right" %>
<%end%> 
</h3>
</br>
<table class = "table table-striped table-bordered table-hover">
  <thead class = "thead-dark">
  <tr>
    <th>Course Identifier</th>
    <th>Section Number</th>
    <th>Schedule</th>
    <th>Location</th>
    <th>Instructor Email</th>
    <th>Status</th>
    <th>Options</th>
  </tr>
 </thead>

  <tbody>
  <% @grader_applications.each do |application| %>
    <%if application.email == current_user.email  || current_user.role=='admin'%>
      <tr>
        <td><%= application.section.course.course_identifier %></td>
        <td><%= application.section.section_number %></td>
        <td><%= application.section.format_days_of_week %></br>
        <%if application.section.time_start != nil %>
          <%= application.section.time_start.strftime("%I:%M %p") %> - <%= application.section.time_end.strftime("%I:%M %p") %>
        <%else%>
          N/A
        <%end%>

        </td>

      <td><%= application.section.location %></td> 
      <td><%= application.section.instructor_email%></td> 
      <td><%= application.status %></td>
      <td>
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
         <label class="btn active">
          <%= link_to 'View', grader_application_path(application), class:"btn btn-outline-primary btn-sm"  %>
         </label>
           <%if application.status == "Pending" %>
           <label class="btn">
           <%= link_to 'Edit', edit_grader_application_path(application), class:"btn btn-outline-primary btn-sm"  %>
          </label>
         <label class="btn">
           <%= button_to "Delete", application, method: :delete, class:"btn btn-outline-danger btn-sm" %>
        </label>
         </div>   
           <%end%>       
      </td>         
    </tr>
  <% end %>
  <% end %>
   </tbody>
</table>


</br>
</br>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/grader_applications/new.html.erb
<h3>New Grader Application</h3>

<%= render "form", grader_application: @grader_application %>

<br>

app/views/grader_applications/show.html.erb
<h3>Your Application

<div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
  <% if @grader_application.status == "Pending"%>
  <label class="btn active">
   <%= link_to 'Edit Application', edit_grader_application_path, class:"btn btn-outline-success float-right"  %>
  </label>
  <%end%>
  <label class="btn">
      <%= link_to "Return to Grader Applications", grader_applications_path, class:"btn btn-outline-primary float-right" %>
  </label>
</div>  
</h3>
</br>

<%= render "form_show", grader_application: @grader_application%>