config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :sections
  resources :courses
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :grader_applications
  resources :permission_requests
  resources :inbox_applications

  put 'inbox_applications/approve'
  put 'inbox_applications/deny'
  put 'permission_requests/approve'
  put 'permission_requests/deny'

  get 'course_fetcher_ui/index'
  post 'course_fetcher_ui/fetch_courses'
  
  #commenting the default home index thing out. This is to have a landing page.
  #get 'home/index'
  root 'home#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/courses_controller.rb
# frozen_string_literal: true
require 'ransack'
# Controller of the Course. Handles business operations here
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :is_admin, only: %i[ new edit create destroy ]

  # GET /courses or /courses.json
  def index
    @q = Course.ransack(params[:q])
    @courses = @q.result
    @pagy, @courses = pagy(Course.ransack(params[:q]).result(distinct: true))
  end

  # GET /courses/1 or /courses/1.json
  def show
    @p = Section.where(course_id: @course.course_id).ransack(params[:p])
    @sections = @p.result
    @pagy, @sections = pagy(Section.where(course_id: @course.course_id).ransack(params[:q]).result(distinct: true))
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.course_id = generate_course_id if @course.course_id.nil?

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: 'Course has been successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:course_id, :catalog_number, :course_description, :course_name, :academic_career)
  end

  # Assign course id for new courses. Always assign 100000 to the current maximum +1.
  def generate_course_id
    max_course_id = Course.maximum(:course_id)
    return max_course_id.nil? ? 100000 : max_course_id + 1
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">

  <h3>
    CSE <%= course.catalog_number %>: <%= course.course_name %>
  </h3>
  <p>
    <strong>Course description:</strong>
    <%= course.course_description %>
  </p>
  <p>
    <strong>Academic career:</strong>
    <%= course.academic_career %>
  </p>

  <p> 
  <div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn active">
 <%= link_to "Go to Course Catalog", courses_path, :class => "btn btn-outline-primary" %>
  </label>
  <% if current_user && current_user.role == "admin" %>
  <label class="btn"> 
    <%= link_to "New section", new_section_path, class:"btn btn-outline-success " %>
</label>
   <label class="btn">
    <%= link_to "Edit", edit_course_path(@course), :class => "btn btn-outline-success " %>
      </label>
    <label class="btn">
    <%= button_to "Delete", @course, method: :delete, :class => "btn btn-outline-danger" %>
      </label>
  <% end %>
  </p>


</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div>
    <%= form.label :catalog_number, 'Catalog Number (in digit format of XXXX.XX or XXXX with an optional H)*' , style: "display: block" %>
    <%= form.text_field :catalog_number, class:'form-control', placeholder: "Example: 2321" %>
  </div>

  <div>
  <%= form.label :course_name, style: "display: block" %>
  <%= form.text_field :course_name, class:'form-control', placeholder: "Example: Course Name" %>
  </div>

  <div>
    <%= form.label :course_description, style: "display: block" %>
    <%= form.text_field :course_description, class:'form-control', placeholder: "Example: This course covers how to enter in course information." %>
  </div>

 
  <div>
  <%= form.label :academic_career, style: "display: block" %>
  <%= form.select :academic_career, %w[Undergraduate Graduate Pre-college Online Non-Degree] %>
</div>
</br>
 <strong>*: For non-semester courses, XXX.XX or XXX is possible</strong>
 </br>
</br>
  <div>
    <%= form.submit class:'btn btn-outline-success' %>
     <%= link_to "Back to courses", courses_path, class:'btn btn-outline-primary' %>
  </div>
 
  </form>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h3>Course Catalog
  <% if current_user && current_user.role == "admin" %>
<div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
  <label class="btn active">
 <%= link_to "Go to Course Fetcher", course_fetcher_ui_index_path, class:"btn btn-outline-primary float-right"%>
  </label>
  <label class="btn">
   <%= link_to "New course", new_course_path,  class:"btn btn-outline-success float-right" %>
    </label>
</div> 
  <% end %>
   <form class="float-right form-inline">
     <%= search_form_for @q do |f| %>
     <%= f.search_field :short_description_or_catalog_number_or_course_name_or_academic_career_cont, class:'form-control mr-sm-2 float-right' %>
     <%= f.submit :submit, class:'btn btn-outline-success my-2 my-sm-o float-right' %> 
    <% end %>
    </form>
  </h3>
<p> For sorting, click on the column you would like to sort.</p>
<div id="courses">
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
      <th><%= sort_link(@q, :catalog_number, class:'text-white')%></th>
      <th><%= sort_link(@q, :course_name, class:'text-white') %></th>
      <th><%= sort_link(@q, :academic_career, class:'text-white') %></th>
      <th >Operations</th>
    </tr>
    </thead>
    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.catalog_number %></td>
        <td><%= course.course_name %></td>
        <td><%= course.academic_career %></td>
        <td>
           <%= link_to "Show Course Details", course, :class => "btn btn-outline-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<strong>Showing <%=@courses.count %> of the <%= Course.count %> courses in the database</strong>
<div class='float-right'> 
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/courses/new.html.erb
<h3>New course</h3>

<%= render "form", course: @course %>

<br>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>


<div id="sections">

  <table class="table table-bordered table-hover">
    <thead class="thead-dark">

    <tr>
      <th>Section Number</th>
      <th>Term ID</th>
      <th>Meeting Days</th>
      <th>Time Start</th>
      <th>Time End</th>
      <th>Instructor</th>
      <th>Num Required Grader</th>
      <th>Current Num Grader</th>
      <th>Operation</th>
    </tr>
    </thead>
    <tbody>
    <%# @sections = @course.sections %>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.section_number %></td>
        <td><%= section.term_id %></td>
        <td><%= section.format_days_of_week %></td>
        <% if section.time_start != nil %>
          <td><%= section.time_start.strftime("%I:%M %p") %></td>
        <% else %>
          <td><%= Section.nil_wrapper(section.time_start) %></td>
        <% end %>
        <% if section.time_start != nil %>
          <td><%= section.time_end.strftime("%I:%M %p") %></td>
        <% else %>
          <td><%= Section.nil_wrapper(section.time_end) %></td>
        <% end %>
        <td><%= Section.nil_wrapper(section.instructor_name) %></td>
        <td><%= section.num_required_graders %></td>
        <td><%= section.current_num_required_graders %></td>
        <td><%= link_to "Section Details", section, :class => "btn btn-outline-primary btn-sm" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<strong>In total of <%= Section.where(course_id: @course.course_id).count %> sections of this course in the
  database</strong>
  <div class='float-right'>  <%== pagy_bootstrap_nav(@pagy) %> </div>
</br>
</br>
<p></p>


</div>